# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest  

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

    steps:
    - name: Checkout repository  
      uses: actions/checkout@v3

    - name: Set up Node.js  
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install    

    - name: Build React App  
      run: yarn build

  deploy:
    runs-on: ubuntu-latest  
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy -- -u "github-actions-bot <support+actions@github.com>"
      
      
